Add support problem annotation and handling exceptions accordingly with RFC7807
WinterFramework/winter pull request #175
Opened 2020-10-25 16:56 UTC by mikhaillazko

Add `ProblemAnnotation` and decorator `problem(status=, title=, detail=, type=, auto_handle=)`
Allow auto generation handlers for problems
Annotate existing winter exceptions
Add tests and app config for test
Update readme
Update version` 4.2.0` and change log

2020-10-25 17:07 UTC, mofr requested changes

2020-10-25 17:07 UTC, mofr commented on CHANGELOG.md
> +### New features
Please add info about changes in setup functions

2020-10-26 06:01 UTC, LeonidKrutovsky approved these changes

2020-10-26 06:57 UTC, mofr approved these changes

2020-10-26 07:28 UTC, berenda-andrey commented on README.md
> +class TodoNotFoundExceptionCustomHandler(winter.web.ExceptionHandler):
Написано NotFound, а кажется что Forbidden

2020-10-26 07:28 UTC, berenda-andrey commented on tests/conftest.py
> +                'DIRS': [app_dir.parent.name + '/templates'],
```suggestion
                'DIRS': [app_dir.parent.name + 'templates'],
```

2020-10-26 07:40 UTC, berenda-andrey commented on winter/web/exceptions/problem_handling.py
> +            for field in fields:
`problem_dict.update(dataclasses.asdict(exception))`
Кажется ты это хотел сделать

2020-10-26 07:43 UTC, berenda-andrey commented on winter/web/__init__.py
> +    generate_problem_handlers()
Надо проверить то что не рано генерируем, может быть еще не все компоненты подхватились, но не уверен, может быть все ок

2020-10-26 09:09 UTC, mikhaillazko commented on tests/conftest.py
> +                'DIRS': [app_dir.parent.name + '/templates'],
`app_dir.parent.name == "tests"` поэтому предложенный вариант не сработает

2020-10-26 09:16 UTC, mikhaillazko commented on winter/web/__init__.py
> +    generate_problem_handlers()
Тут ты верно подметил, пока это проблема не решена. Как временное решение мы явно контролируем вызов setup функции и перед ее вызовом делаем импорт урлов, которые тянут за собой инициализацию всего остального.
Сейчас это делается в AppConfig.ready()

2020-10-26 09:32 UTC, mofr approved these changes

2020-10-26 09:35 UTC, merged

2020-10-26 16:02 UTC, berenda-andrey commented on tests/conftest.py
> +                'DIRS': [app_dir.parent.name + '/templates'],
блин, я хотел написать так
` 'DIRS': [app_dir.parent / 'templates'],`

2020-10-26 16:03 UTC, berenda-andrey commented on tests/conftest.py
> +                'DIRS': [app_dir.parent.name + '/templates'],
тогда не будем зависеть от операционной системы(в винде по другому пути)