Add typings and use List instead set() at domain_event_dispatcher
WinterFramework/winter pull request #180
Opened 2020-11-10 15:18 UTC by DmitryKhursevich

With the current implementation, we use set()  at DomainEventDispatcher, hence there is non-deterministic order of execution domain event’s handlers. It can lead to deadlock. 

For example, if we have 2 handlers on the domain event, which insert a row to the according tables, and if execution order between transactions is different, then there is a deadlock on insert statement: transaction 1 inserts to first table and waits for the lock at second table, and simultaneously transaction 2 inserts to second table and waits for lock at first table.

Set() has been replaced by List with "already exist" check.

2020-11-10 20:31 UTC, berenda-andrey commented on winter_ddd/domain_event_dispatcher.py
> +        self._event_type_to_event_filter_map: Dict[Type[DomainEvent], List[EventFilter]] = {}
```suggestion
        self._event_type_to_event_filters_map: Dict[Type[DomainEvent], List[EventFilter]] = {}
```
Там список, поэтому кажется надо добавить s

2020-11-10 20:31 UTC, berenda-andrey commented on winter_ddd/domain_event_dispatcher.py
> +            event_filter = self._event_type_to_event_filter_map.setdefault(event_type, [])
```suggestion
            event_filters = self._event_type_to_event_filter_map.setdefault(event_type, [])
```

2020-11-10 20:31 UTC, berenda-andrey commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
```suggestion
            if subscription.event_filter not in event_filters:
```

2020-11-10 20:33 UTC, berenda-andrey commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
Это операция будет работать за линейное время, можно использовать словарь, он гарантирует порядок и константная проверка на наличие(значение наверное можно использовать None)

2020-11-11 11:40 UTC, mikhaillazko commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
@berenda-andrey ты имеешь ввиду OrdredDict или предлагаешь завязаться на внутренности реализации? на сколько я знаю python не давал обещание не ломать это поведение в будущем

2020-11-11 11:57 UTC, berenda-andrey commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
Начиная с python3.7 документировано и можно полагаться на то что словарь имеет порядок по вставке элементов. С этого момента прошло больше 2х лет(3.7 вышел 27 июня 2018) и кажется это прошло проверку временем и можно на это полагаться

2020-11-11 12:00 UTC, berenda-andrey commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
Выглядит так что не только в python так, но и в PHP(не уверен https://stackoverflow.com/questions/7510383/does-php-have-an-ordered-dictionary)

2020-11-11 12:02 UTC, berenda-andrey commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
И вот еще ссылка:  https://github.com/naftaliharris/tauthon/issues/86#issuecomment-381495656

2020-11-11 12:23 UTC, DmitryKhursevich commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
@berenda-andrey  

вот так?
```
      self._event_type_to_event_filters_map: Dict[Type[DomainEvent], Dict[EventFilter, None]] = {}

       for event_type in subscription.event_filter:
            event_filters = self._event_type_to_event_filters_map.setdefault(event_type, {})
            if subscription.event_filter not in event_filters:
                event_filters[subscription.event_filter] = None
```
-------
```
def dispatch(self, events: Iterable[DomainEvent]):
            event_filters = self._event_type_to_event_filters_map.get(event_type, {})
            for event_filter in event_filters.keys():
                filtered_events.setdefault(event_filter, []).append(event)
```

единственное, насоклько я понимаю, сейчас же у нас на проекте 3.6 используется?

2020-11-11 12:34 UTC, mofr commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
Я бы предпочел более явное намерение чем полагание на порядок элементов в dict, тем более сктруктура и так уже вложенная, а еще и ненужный None для каждого ключа будет лежать.
Как вариант можно держать И list И set, один для порядка, другой для проверки.

2020-11-11 12:38 UTC, DmitryKhursevich commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
@berenda-andrey  @mikhaillazko  тогда как в итоге?

- просто List
- Dict с None
- List и Set

2020-11-11 13:04 UTC, berenda-andrey commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
Мне все варианты норм, но голосую за dict.
Либо можно выбрать контейнер в зависимости от версии python (>=3.7 - dict, <3.7 - OrderedDict)

2020-11-11 13:06 UTC, mofr commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
Мне норм варианты 1 и 3, голосую против 2.

2020-11-12 04:41 UTC, DmitryKhursevich commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
@mikhaillazko

2020-11-12 10:12 UTC, mikhaillazko commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
я голосую за 1. сначала корректность а потом уже перфоманс, если будут с ним проблемы, оптимизировать понятно как

2020-11-12 10:22 UTC, DmitryKhursevich commented on winter_ddd/domain_event_dispatcher.py
> +            if subscription.event_filter not in event_filter:
@berenda-andrey 

тогда вроде бы пришли к 1ому варианту - то есть как сейчас:
- Вариант с dict не очевидный по коду получится + не надежный, все таки это внутреннее устройство dict  и при возможности лучше не надеятся на его детерминированность
- вариант с List и Set прибавит сложность коду 

И получается же эта проверка выполняется на добавление subcription, то есть при инициализации, а не во время работы с events + подписок не больше 100 -> на вряд ли там будет заметная разница в перфомансе

2020-11-12 10:25 UTC, mofr requested changes
Please add a test to check the order of handlers' invocation.

2020-11-13 07:51 UTC, mofr approved these changes

2020-11-13 09:04 UTC, merged