Add function to get the list of all routes by passing package name
WinterFramework/winter pull request #249
Opened 2023-02-03 12:09 UTC by EvgenySmekalin

Not sure about filenames and what should be tested in test

2023-02-03 12:10 UTC, EvgenySmekalin commented
Not sure about filenames and what should be tested in the test

2023-02-03 13:20 UTC, mofr requested changes

2023-02-03 13:20 UTC, mofr commented on tests/web/test_autodiscover.py
> +
filename typo: test_autodiscoverY.py

2023-02-03 13:20 UTC, mofr commented on winter/web/autodiscovery.py
> +def get_routes_by_package(package_name: str) -> List[Route]:
I would rename to `get_routes_for_package` to be consistent with `create_django_urls_for_package`
Or shorter versions: `find_package_routes`/`get_package_routes`

(not a blocker)

2023-02-03 15:43 UTC, mofr approved these changes

2023-02-03 15:43 UTC, mofr commented on CHANGELOG.md
> +- find_package_routes: function that returns a list of routes by the package name
Please specify package as well (winter.web)

2023-02-03 15:45 UTC, mofr commented on winter/web/autodiscovery.py
> +from winter.web.routing import get_route
I think tests failed due to these absolute import within a single package (winter.web)

2023-02-04 13:46 UTC, pristupa approved these changes

2023-02-05 12:54 UTC, mikhaillazko approved these changes

2023-02-06 09:47 UTC, mofr approved these changes

2023-02-06 09:47 UTC, mofr commented on tests/api/package/subpackage/api_4.py
> +class API4:
Probably it would be better to replace it with a valid code to avoid possible confusion. For example something without routes and api mentions.

2023-02-06 13:05 UTC, merged