Add request_header feature
WinterFramework/winter pull request #253
Opened 2023-02-07 09:01 UTC by nekitmish

```
@winter.route_get('url/')
@winter.request_header('X-Auth-CompanyID', to='company_id')
def some_method(self, company_id: str):
  print(company_id)
```

2023-02-07 09:52 UTC, pristupa requested changes

2023-02-07 09:52 UTC, pristupa commented on winter/web/request_header_resolver.py
> +        self._cache = {}
why cache?

2023-02-07 09:52 UTC, pristupa commented on winter/web/request_header_resolver.py
> +        annotation = next(  # pragma: no cover
why no cover here?

2023-02-07 11:14 UTC, nekitmish commented on winter/web/request_header_resolver.py
> +        annotation = next(  # pragma: no cover
just forgot to delete

2023-02-07 11:14 UTC, nekitmish commented on winter/web/request_header_resolver.py
> +        self._cache = {}
just forgot to delete

2023-02-07 11:48 UTC, pristupa approved these changes

2023-02-07 11:48 UTC, merged

2025-04-30 08:02 UTC, rushduhhp approved these changes